apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "django-app.fullname" . }}-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "django-app-secrets-v2" # Назва з Terraform
        objectType: "secretsmanager"
        jmesPath:
          - path: "SECRET_KEY"
            objectAlias: "SECRET_KEY"
          - path: "DATABASE_PASSWORD"
            objectAlias: "DATABASE_PASSWORD"
  # Ця секція створює звичайний K8s Secret із завантажених даних
  secretObjects:
    - secretName: {{ include "django-app.fullname" . }}-synced-secrets
      type: Opaque
      data:
        - objectName: "SECRET_KEY"
          key: "SECRET_KEY"
        - objectName: "DATABASE_PASSWORD"
          key: "DATABASE_PASSWORD"